eyetracking/apps/participants/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.ParticipantList.as_view(), name='list'),
    url(r'^new/$', views.ParticipantCreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.ParticipantDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.ParticipantUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', views.ParticipantDelete.as_view(), name='delete'),
]

eyetracking/eyetracking/urls.py
from django.conf.urls import include, url
from apps.tracker import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^tracker/', include('apps.tracker.urls', namespace='tracker')),
    url(r'^images/', include('apps.images.urls', namespace='images')),
    url(r'^participants/', include('apps.participants.urls', namespace='participants')),
    url(r'^aoi/', include('apps.aoi.urls', namespace='aoi')),
    url(r'^statistics/', include('apps.statistics.urls', namespace='statistics')),
    url(r'^trials/', include('apps.trials.urls', namespace='trials'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eyetracking/apps/participants/models.py
from django.core.urlresolvers import reverse
from django.db import models
import numpy as np


class Participant(models.Model):
    first_name = models.CharField(verbose_name='Full Name', max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.PositiveSmallIntegerField(verbose_name='Age', default=0)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(verbose_name='Gender', max_length=1, choices=GENDER_CHOICES)
    comments = models.TextField(blank=True)

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('participants:detail', args=[str(self.id)])

    def get_total(self):
        return Participant.objects.count()

    def count_gender(self, total):
        male = Participant.objects.filter(gender='M').count()
        female = total - male

        return  male, female

    def mean(self):
        participants_age = Participant.objects.values_list('age', flat=True)

        return np.mean(participants_age)

    def sd(self):
        participants_age = Participant.objects.values_list('age', flat=True)

        return np.std(participants_age)

eyetracking/apps/participants/forms.py
from django import forms
from .models import Participant


class ParticipantForm(forms.ModelForm):
    first_name = forms.CharField(label='First name', widget=forms.TextInput(attrs={'autofocus':''}))
    age = forms.IntegerField(min_value=1, widget=forms.TextInput(),
                             error_messages={'invalid': 'Enter a valid value',
                                             'min_value':'Value must be greater than or equal 1'})
    comments = forms.Textarea()

    class Meta:
        model = Participant
        fields = ['first_name', 'last_name', 'age', 'gender', 'comments']

eyetracking/apps/participants/views.py
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db.models import Q
from vanilla import CreateView, DetailView, UpdateView, RedirectView
from django_tables2 import SingleTableView
from .forms import ParticipantForm
from .models import Participant
from .tables import ParticipantTable


class ParticipantList(SingleTableView):
    model = Participant
    table_class = ParticipantTable
    table_pagination = {'per_page': 10}

    # Additional data
    total = Participant().get_total()
    male, female = Participant().count_gender(total)
    mean = Participant().mean()
    sd = Participant().sd()

    def get_table_data(self):
        data = Participant.objects.all().order_by('first_name')
        if self.request.GET.get('search'):
            value = self.request.GET.get('search')
            if value:
                data = data.filter(Q(first_name__contains=value) | Q(last_name__contains=value)
                                   | Q(gender=value) | Q(age__contains=value))
        return data

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ParticipantList, self).get_context_data(**kwargs)

        search = ''
        if self.request.GET.get('search'):
            search = self.request.GET.get('search')
        context['search'] = search

        return context


class ParticipantCreate(SuccessMessageMixin, CreateView):
    model = Participant
    form_class = ParticipantForm
    template_name_suffix = '_create'
    success_url = reverse_lazy('participants:list')
    success_message = "Participant '%(first_name)s %(last_name)s' was created successfully"


class ParticipantDetail(DetailView):
    model = Participant


class ParticipantUpdate(SuccessMessageMixin, UpdateView):
    model = Participant
    form_class = ParticipantForm
    template_name_suffix = '_update'
    success_url = reverse_lazy('participants:list')
    success_message = "Participant '%(first_name)s %(last_name)s' was updated successfully"


class ParticipantDelete(RedirectView):
    model = Participant

    def get_redirect_url(self, *args, **kwargs):
        self.url = reverse_lazy('participants:list')
        self.permanent = True
        model = get_object_or_404(Participant, pk=kwargs['pk'])
        name = model.first_name + ' ' + model.last_name
        model.delete()
        messages.success(self.request,"Participant '" + name + "' was deleted successfully")
        return super(ParticipantDelete, self).get_redirect_url(*args, **kwargs)

eyetracking/apps/participants/templates/participants/participant_actions.html
<a class="btn btn-primary btn-sm tooltip-btn" data-toggle="tooltip" data-placement="top" data-original-title="Update" href="{% url 'participants:update' record.pk %}"><i class="glyphicon glyphicon-edit"></i></a>

<form class="form-inline" method="POST" action="{% url 'participants:delete' record.pk %}">
    {% csrf_token %}
    <button onclick="return confirm('Are you sure you want to delete \'{{ record.name }}\'?')" type="submit" class="btn btn-sm btn-danger tooltip-btn" data-toggle="tooltip" data-placement="top" data-original-title="Delete">
        <i class="glyphicon glyphicon-trash"></i>
    </button>
</form>

eyetracking/apps/participants/templates/participants/participant_create.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %} Create Participant {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='participants' %}
{% endblock %}

{% block page_title %} Create Participant {% endblock %}

{% block content %}
	{% include 'participants/participant_form.html' %}
{% endblock %}

eyetracking/apps/participants/templates/participants/participant_detail.html
{% extends "base.html" %}

{% block title %} View Participant {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='participants' %}
{% endblock %}

{% block page_title %} View Participant {% endblock %}

{% block actions %}
    <a class="btn btn-primary" href="{% url 'participants:update' object.pk %}" role="button"><i class="glyphicon glyphicon-edit"></i> Update</a>

    <form class="form-inline" method="POST" action="{% url 'participants:delete' object.pk %}">
        {% csrf_token %}
        <button onclick="return confirm('Are you sure you want to delete?')" type="submit" class="btn btn-danger tooltip-btn" data-toggle="tooltip" data-placement="top" data-original-title="Delete">
            <i class="glyphicon glyphicon-trash"></i> Delete
        </button>
    </form>
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <tr>
            <td><strong>Name</strong></td>
            <td>{{ object.first_name }} {{ object.last_name }}</td>
        </tr>
        <tr>
            <td><strong>Gender</strong></td>
            <td>{{ object.get_gender_display }}</td>
        </tr>
        <tr>
            <td><strong>Age</strong></td>
            <td>{{ object.age }}</td>
        </tr>
         <tr>
            <td><strong>Comments</strong></td>
            <td>{{ object.comments }}</td>
        </tr>
    </table>
{% endblock %}

eyetracking/apps/participants/templates/participants/participant_form.html
{% load bootstrap3 %}

<form method="post" class="form-horizontal">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
      <button type="submit" class="btn btn-primary">Save</button>
  {% endbuttons %}
</form>

eyetracking/apps/participants/templates/participants/participant_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title %} Manage Participants {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='participants' %}
{% endblock %}

{% block page_title %} Manage Participants {% endblock %}

{% block actions %}
    <a class="btn btn-success" href="{% url 'participants:create' %}" role="button"><i class="glyphicon glyphicon-plus"></i> Create</a>
{% endblock %}

{% block content %}
    {% include 'participants/participant_search.html' %}

    <div class="container-fluid">
        <div class="col-lg-10">
            {% render_table table "table.html" %}
        </div>
        <div class="col-lg-2 well" style="margin-top: 20px;">
             <div class="col-lg-12" >
                <p>Mean = {{ view.mean }}</p>
                <p>SD = {{ view.sd|floatformat:4 }}</p>
                <p><i class="fa fa-male fa-2x"></i> = {{ view.male }}</p>
                <p><i class="fa fa-female fa-2x"></i> = {{ view.female }}</p>
            </div>
        </div>
    </div>
{% endblock %}

eyetracking/apps/participants/templates/participants/participant_search.html
<hr>
<div class="row">
    <div class="col-lg-10">
        <div class="col-lg-6">
        </div>
        <div class="col-lg-6">
            <form role="search">
                <div class="input-group">
                    <input name="search" value="{{ search }}" type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i> </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<br>

eyetracking/apps/participants/templates/participants/participant_update.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %} Update Participant {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='participants' %}
{% endblock %}

{% block page_title %} Update Participant {% endblock %}

{% block content %}
	{% include 'participants/participant_form.html' %}
{% endblock %}