eyetracking/apps/images/urls.py
from django.conf.urls import url
from django.views.generic import DetailView
from . import views
from .models import Image


urlpatterns = [
    url(r'^$', views.index, name='index_images'),
    url(r'^add$', views.add, name='add_images'),
    url(r'^(?P<pk>\d+)/update$', views.update, name='update_image'),
    url(r'^(?P<pk>\d+)/detail$', DetailView.as_view(model=Image, template_name="images/detail.html"), name="detail_image"),
    url(r'^(?P<pk>\d+)/delete$', views.delete, name='delete_image'),
    url(r'^upload$', views.upload, name='upload_image'),
    url(r'^(?P<pk>\d+)/upload_delete$', views.upload_delete, name='upload_delete'),
]

eyetracking/eyetracking/urls.py
from django.conf.urls import include, url
from apps.tracker import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^tracker/', include('apps.tracker.urls', namespace='tracker')),
    url(r'^images/', include('apps.images.urls', namespace='images')),
    url(r'^participants/', include('apps.participants.urls', namespace='participants')),
    url(r'^aoi/', include('apps.aoi.urls', namespace='aoi')),
    url(r'^statistics/', include('apps.statistics.urls', namespace='statistics')),
    url(r'^trials/', include('apps.trials.urls', namespace='trials'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eyetracking/apps/images/models.py
from django.db import models
from uuid_upload_path import upload_to
from django_resized import ResizedImageField
import django_filters


class Image(models.Model):

    image = models.ImageField(upload_to=upload_to, height_field='height', width_field='width')
    resized_image = ResizedImageField(verbose_name="Image", size=[150, 150], quality=90, upload_to=upload_to)
    original_name = models.CharField(verbose_name="Name", max_length=255, default='default')
    size = models.CharField(verbose_name="Size", max_length=30, default='')
    width = models.PositiveIntegerField(verbose_name="Resolution", default=0)
    height = models.PositiveIntegerField(default=0)

    @classmethod
    def human_size(cls, number_bytes):
        suffixes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB']
        if number_bytes == 0:
            return '0 B'
        i = 0
        while number_bytes >= 1024 and i < len(suffixes) - 1:
            number_bytes /= 1024.
            i += 1
        f = ('%.2f' % number_bytes).rstrip('0').rstrip('.')
        return '%s %s' % (f, suffixes[i])


class ImageFilter(django_filters.FilterSet):

    class Meta:
        model = Image
        fields = ['original_name']

eyetracking/apps/images/forms.py
from django import forms
from .models import Image


class PhotoForm(forms.ModelForm):

    original_name = forms.CharField(label='Name', max_length=255, error_messages={'required': 'Name is required.'})

    class Meta:
        model = Image
        fields = ('original_name',)

eyetracking/apps/images/views.py
import os
from django.shortcuts import render
from django_tables2 import RequestConfig
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import transaction
from django.views.decorators.http import require_POST
from jfu.http import upload_receive, UploadResponse, JFUResponse
from eyetracking.settings import MEDIA_URL
from apps.aoi.models import AOI
from .models import Image
from .tables import PhotoTable
from .forms import PhotoForm


def index(request):

    model = Image.objects.all()
    table = PhotoTable(model)
    RequestConfig(request, paginate={'per_page': 10}).configure(table)

    return render(request, 'images/index.html', {'model':model, 'table': table})


def add(request):

    return render(request, 'images/add.html', {})


def update(request, pk):

    model = get_object_or_404(Image, pk=pk)

    if request.method == 'POST':
        form = PhotoForm(data=request.POST, instance=model)

        if form.is_valid():
            form.save()
            messages.success(request, 'Image Updated')
            return HttpResponseRedirect(reverse('images:index_images'))
    else:
        form = PhotoForm(None, instance=model)

    return render(request, 'images/update.html', {'form': form})


@transaction.atomic
def delete(request, pk):

    model = get_object_or_404(Image, pk=pk)
    model.delete()
    os.unlink(model.image.path)
    os.unlink(model.resized_image.path)

    AOI.objects.filter(image=pk).delete()

    messages.success(request, 'Image Deleted')

    return HttpResponseRedirect(reverse('images:index_images'))


@require_POST
def upload(request):

    image = upload_receive(request)
    size = image.size

    model = Image(image=image, resized_image=image)
    basename = os.path.basename(model.image.path)
    model.original_name = os.path.basename(model.image.path)
    model.size = Image.human_size(size)
    model.save()

    file_dict = {
        'name': basename,
        'size': size,

        'url': MEDIA_URL + str(model.image),
        'thumbnailUrl': MEDIA_URL + str(model.resized_image),

        'deleteUrl': reverse('images:upload_delete', kwargs={'pk': model.pk}),
        'deleteType': 'POST',
    }

    return UploadResponse(request, file_dict)


@require_POST
@transaction.atomic
def upload_delete(request, pk):

    success = True
    try:
        model = Image.objects.get(pk=pk)
        os.unlink(model.image.path)
        os.unlink(model.resized_image.path)
        model.delete()
        AOI.objects.filter(image=pk).delete()
    except Image.DoesNotExist:
        success = False

    return JFUResponse(request, success)

eyetracking/apps/images/templates/images/actions.html
<a class="btn btn-primary btn-sm tooltip-btn" data-toggle="tooltip" data-placement="top" data-original-title="Update" href="{% url 'images:update_image' record.pk %}"><i class="glyphicon glyphicon-edit"></i></a>

<form class="form-inline" method="POST" action="{% url 'images:delete_image' record.pk %}">
    {% csrf_token %}
    <button onclick="return confirm('Are you sure you want to delete \'{{ record.name }}\'?')" type="submit" class="btn btn-sm btn-danger tooltip-btn" data-toggle="tooltip" data-placement="top" data-original-title="Delete">
        <i class="glyphicon glyphicon-trash"></i>
    </button>
</form>

eyetracking/apps/images/templates/images/add.html
{% extends "base.html" %}
{% load static %}
{% load jfutags %}

{% block title %} Add Images {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='images' %}
{% endblock %}

{% block page_title %} Add Images {% endblock %}

{% block content %}
    {% jfu 'images/photo_upload_form.html' 'images:upload_image' %}
{% endblock %}

eyetracking/apps/images/templates/images/carousel.html
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="carousel slide" id="carousel2">
                <ol class="carousel-indicators">
                    {% for photo in model %}
                        <li data-slide-to="{{ forloop.counter0 }}" data-target="#carousel2"  class="{% if forloop.counter0 == 0 %}active{% endif %}"></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for photo in model %}
                        <div class="item {% if forloop.counter0 == 0 %}active{% endif %}">
                            <img alt="image"  class="img-responsive" src="{{ MEDIA_URL }}{{ photo.image }}">
                            <div class="carousel-caption">
                                <p>{{ photo.original_name }} - {{ photo.size }} - {{ photo.width }} x {{ photo.height }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a data-slide="prev" href="#carousel2" class="left carousel-control">
                    <span class="icon-prev"></span>
                </a>
                <a data-slide="next" href="#carousel2" class="right carousel-control">
                    <span class="icon-next"></span>
                </a>
            </div>
        </div>
    </div>
</div>

eyetracking/apps/images/templates/images/detail.html
{% extends "base.html" %}

{% block title %} View Image {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='images' %}
{% endblock %}

{% block page_title %} View Image {% endblock %}

{% block actions %}
    <a class="btn btn-primary" href="{% url 'images:update_image' object.id %}" role="button"><i class="glyphicon glyphicon-edit"></i> Update</a>

    <form class="form-inline" method="POST" action="{% url 'images:delete_image' object.id %}">
        {% csrf_token %}
        <button onclick="return confirm('Are you sure you want to delete?')" type="submit" class="btn btn-danger tooltip-btn" data-toggle="tooltip" data-placement="top" data-original-title="Delete">
            <i class="glyphicon glyphicon-trash"></i> Delete
        </button>
    </form>
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <tr>
            <td><strong>Photo</strong></td>
            <td><img class="img-responsive" alt="{{ object.name }}" src="{{ MEDIA_URL }}{{ object.image }}"></td>
        </tr>
        <tr>
            <td><strong>Name</strong></td>
            <td>{{ object.original_name }}</td>
        </tr>
        <tr>
            <td><strong>Size</strong></td>
            <td>{{ object.size }}</td>
        </tr>
        <tr>
            <td><strong>Resolution</strong></td>
            <td>{{ object.width }} x {{ object.height }}</td>
        </tr>
    </table>
{% endblock %}

eyetracking/apps/images/templates/images/form.html
{% load bootstrap3 %}

<form method="post" class="form-horizontal">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
      <button type="submit" class="btn btn-primary">Save</button>
  {% endbuttons %}
</form>

eyetracking/apps/images/templates/images/index.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title %} Manage Images {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='images' %}
{% endblock %}

{% block page_title %} Manage Images {% endblock %}

{% block actions %}
    <a class="btn btn-success" href="{% url 'images:add_images' %}" role="button"><i class="fa fa-plus"></i> Add</a>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg"><i class="fa fa-picture-o"></i> Preview</button>
{% endblock %}

{% block content %}
    {% render_table table "table.html" %}
    {% include 'images/carousel.html' %}
{% endblock %}

eyetracking/apps/images/templates/images/photo_upload_form.html
{% extends 'jfu/upload_form.html' %}

{% block JS_OPTS %}
sequentialUploads: true,
acceptFileTypes: /(\.|\/)(png|gif|jpe?g)$/i
{% endblock %}

{% block CSS_BOOTSTRAP %}{% endblock %}
{% block JS_BOOTSTRAP %}{% endblock %}
{% block JS_JQUERY %}{% endblock %}

eyetracking/apps/images/templates/images/update.html
{% extends "base.html" %}

{% block title %} Update Image {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='images' %}
{% endblock %}

{% block page_title %} Update Image {% endblock %}

{% block content %}
    {% include "images/form.html" %}
{% endblock %}