eyetracking/apps/trials/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.TrialList.as_view(), name='list'),
    url(r'^upload/$', views.TrialCreate.as_view(), name='upload'),
    url(r'^(?P<pk>\d+)/$', views.TrialDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update', views.TrialUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', views.TrialDelete.as_view(), name='delete'),
]

eyetracking/eyetracking/urls.py
from django.conf.urls import include, url
from apps.tracker import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^tracker/', include('apps.tracker.urls', namespace='tracker')),
    url(r'^images/', include('apps.images.urls', namespace='images')),
    url(r'^participants/', include('apps.participants.urls', namespace='participants')),
    url(r'^aoi/', include('apps.aoi.urls', namespace='aoi')),
    url(r'^statistics/', include('apps.statistics.urls', namespace='statistics')),
    url(r'^trials/', include('apps.trials.urls', namespace='trials'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eyetracking/apps/trials/models.py
from django.core.urlresolvers import reverse
from django.db import models, transaction
from django.db.models import signals, Avg, Q
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
import numpy as np
from ..statistics.utils import Utils
from ..participants.models import Participant
from ..images.models import Image


class Trial(models.Model):
    calibration_points = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='trials/')
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    percentage_samples = models.FloatField(blank=True, null=True)
    participant = models.ForeignKey(Participant, blank=True, null=True)
    image = models.ForeignKey(Image, blank=True, null=True)
    errors = models.IntegerField(blank=True, default='0')
    resolved = models.BooleanField(blank=True, default='')
    level = models.IntegerField(blank=True, default=1)

    def get_absolute_url(self):
        return reverse('trials:detail', args=[str(self.id)])

    def handle_uploaded_file(self, file):
        # Read file
        f = open(settings.MEDIA_ROOT + '/' + file, 'r')
        lines = f.readlines()
        f.close()

        start_gaze_data = False
        data = {}
        eye_data = []

        # Loop lines
        for i in range(len(lines)):
            line = lines[i].replace('\n','').replace('\r','').split('\t')
            length_line = len(line)

            # If exist data in the line
            if start_gaze_data == True and length_line >2:

                if 'stop_recording' in line[3]:
                    data['end_date'] = line [1]
                else:

                    eye = {'timestamp':line[0],
                           'time':line[1],
                           'fix':line[2],
                           'state':line[3],
                           'rawx':line[4],
                           'rawy':line[5],
                           'avgx':line[6],
                           'avgy':line[7],
                           'psize':line[8],
                           'Lrawx':line[9],
                           'Lrawy':line[10],
                           'Lavgx':line[11],
                           'Lavgy':line[12],
                           'Lpsize':line[13],
                           'Lpupilx':line[14],
                           'Lpupily':line[15],
                           'Rrawx':line[16],
                           'Rrawy':line[17],
                           'Ravgx':line[18],
                           'Ravgy':line[19],
                           'Rpsize':line[20],
                           'Rpupilx':line[21],
                           'Rpupily':line[22],
                           'Distance': line[23]}

                    eye_data.append(eye)

            # Get trial data
            elif line[0] == 'MSG':
                if 'Participant' in line[3]:
                    data['participant'] = line[4]
                elif 'Image' in line[3]:
                    data['image'] = line[4]
                elif 'Calibration' in line[3]:
                    data['calibration_points'] = line[4]
                elif 'Comments' in line[3]:
                    data['comments'] = line[4]
                elif 'start_recording' in line[3]:
                    data['start_date'] = line [1]
                    start_gaze_data = True

        return data, eye_data

    def get_total(self):
        return Trial.objects.count()

    def get_percentage_valid(self, total):
        valid_trials = Trial.objects.filter(percentage_samples__gte=79.99).count()

        percentage_valid = (valid_trials * 100)/total

        return round(percentage_valid, 2)

    def get_percentage_solved(self, total):
        solved_trials = Trial.objects.filter(resolved=True).count()

        percentage_solved = (solved_trials * 100)/total

        return round(percentage_solved, 2)


class TrialFeatures(models.Model):
    baseline = models.FloatField()
    apcps = models.FloatField()
    mpd = models.FloatField()
    mpdc = models.FloatField()
    peak = models.FloatField(default=0.0)
    peak_change = models.FloatField(default=0.0)
    sd = models.FloatField(default=0.0)
    trial = models.ForeignKey(Trial)

    def get_totals(self, level, participant = '', search = ''):

        apcps = 0.0
        apcps_array = []
        mpd = 0.0
        mpd_array = []
        mpdc = 0.0
        mpdc_array = []
        peak = 0.0
        peak_array = []
        peak_change = 0.0
        peak_change_array = []
        sd = 0.0
        sd_array = []
        trials_num = 0

        if participant:
            trials = Trial.objects.filter(level=level, participant=participant, percentage_samples__gte=79.99, resolved = True)
        else:
            trials = Trial.objects.filter(level=level, percentage_samples__gte=79.99, resolved = True)

        if search:
            trials_search = trials.filter(Q(participant__first_name__contains=search) | Q(participant__last_name__contains=search)
                               | Q(image__original_name__contains=search))
        else:
            trials_search = trials

        trials_errors = trials.aggregate(Avg('errors'))
        errors = round(trials_errors['errors__avg'], 4) if trials_errors['errors__avg'] else 0.0

        for trial in trials_search:
            features = TrialFeatures.objects.filter(trial=trial.pk).aggregate(Avg('apcps'), Avg('mpd'), Avg('mpdc'), Avg('peak'), Avg('peak_change'), Avg('sd'))
            apcps_array.append(features['apcps__avg'])
            mpd_array.append(features['mpd__avg'])
            mpdc_array.append(features['mpdc__avg'])
            peak_array.append(features['peak__avg'])
            peak_change_array.append(features['peak_change__avg'])
            sd_array.append(features['sd__avg'])

        if len(apcps_array) > 0:
            apcps = round(np.mean(apcps_array),4)
            mpd = round(np.mean(mpd_array), 4)
            mpdc = round(np.mean(mpdc_array),4)
            peak = round(np.mean(peak_array), 4)
            peak_change = round(np.mean(peak_change_array), 4)
            sd = round(np.mean(sd_array), 4)
            trials_num= len(apcps_array)

        return {'apcps':apcps, 'mpd':mpd, 'mpdc':mpdc, 'errors':errors, 'peak':peak, 'peak_change':peak_change, 'sd':sd, 'trials_num':trials_num}


class TrialData(models.Model):
    timestamp = models.DateTimeField()
    time = models.IntegerField()
    fix = models.BooleanField()
    state = models.PositiveSmallIntegerField()
    raw_x = models.FloatField()
    raw_y = models.FloatField()
    avg_x = models.FloatField()
    avg_y = models.FloatField()
    pupil_size = models.FloatField()
    left_raw_x = models.FloatField()
    left_raw_y = models.FloatField()
    left_avg_x = models.FloatField()
    left_avg_y = models.FloatField()
    left_pupil_size = models.FloatField()
    left_pupil_x = models.FloatField()
    left_pupil_y = models.FloatField()
    right_raw_x = models.FloatField()
    right_raw_y = models.FloatField()
    right_avg_x = models.FloatField()
    right_avg_y = models.FloatField()
    right_pupil_size = models.FloatField()
    right_pupil_x = models.FloatField()
    right_pupil_y = models.FloatField()
    distance = models.FloatField()
    trial = models.ForeignKey(Trial)

    @classmethod
    def percentage_samples(self, trial):
        total = self.objects.filter(trial=trial).count()
        missing = self.objects.filter(left_pupil_size=0, right_pupil_size=0, trial=trial).count()

        percentage_missing = (missing * 100.00)/total
        percentage_good = 100 - percentage_missing

        return round(percentage_good, 2)

    @classmethod
    def is_float(self, value):
        try:
            float(value)
        except ValueError:
            return False
        else:
            return True

@receiver(post_save, sender=Trial)
def update_trial(sender, instance, created, **kwargs):

    if created:

        # Disconnect signal to avoid recursion
        signals.post_save.disconnect(update_trial, sender=sender)

        try:
            # Get data file
            data, eye_data = Trial().handle_uploaded_file(str(instance.file))

            # Get instances
            participant = Participant.objects.get(id=data['participant'])
            image = Image.objects.get(id=data['image'])

            with transaction.atomic():

                # Add eye data
                for eye in eye_data:

                    TrialData.objects.create(timestamp=eye['timestamp'],
                                               time=eye['time'],
                                               fix=eye['fix'],
                                               state=eye['state'],
                                               raw_x=eye['rawx'],
                                               raw_y=eye['rawy'],
                                               avg_x=eye['avgx'],
                                               avg_y=eye['avgy'],
                                               pupil_size=eye['psize'],
                                               left_raw_x=eye['Lrawx'],
                                               left_raw_y=eye['Lrawy'],
                                               left_avg_x=eye['Lavgx'],
                                               left_avg_y=eye['Lavgy'],
                                               left_pupil_size=eye['Lpsize'],
                                               left_pupil_x=eye['Lpupilx'],
                                               left_pupil_y=eye['Lpupily'],
                                               right_raw_x=eye['Rrawx'],
                                               right_raw_y=eye['Rrawy'],
                                               right_avg_x=eye['Ravgx'],

eyetracking/apps/trials/forms.py
from django import forms
from .models import Trial


class TrialUploadForm(forms.ModelForm):
	file = forms.FileField()

	class Meta:
		model = Trial
		fields = ['file']

class TrialUpdateForm(forms.ModelForm):
	resolved = forms.BooleanField(label='Solved', required=False)
	LEVELS = (
        (1, 'Level 1'),
        (2, 'Level 2'),
		(3, 'Level 3'),
    )
	level = forms.ChoiceField(LEVELS)

	class Meta:
		model = Trial
		fields = ['resolved', 'level', 'errors', 'comments']

eyetracking/apps/trials/views.py
import os
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db import IntegrityError, transaction
from django.db.models import Q
from vanilla import CreateView, DetailView, UpdateView, RedirectView
from django_tables2 import SingleTableView
from .forms import TrialUploadForm, TrialUpdateForm
from .models import Trial, TrialData
from .tables import TrialTable


class TrialList(SingleTableView):
    model = Trial
    table_class = TrialTable
    table_pagination = {'per_page': 10}

    def get_table_data(self):
        data = Trial.objects.all().order_by('participant__first_name')
        if self.request.GET.get('search'):
            value = self.request.GET.get('search')
            if value:
                data = data.filter(Q(image__original_name__contains=value) | Q(participant__first_name__contains=value)
                                   | Q(participant__last_name__contains=value) | Q(percentage_samples__contains=value))
        return data

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TrialList, self).get_context_data(**kwargs)

        search = ''
        if self.request.GET.get('search'):
            search = self.request.GET.get('search')
        context['search'] = search

        trial = Trial()
        total = trial.get_total()
        if total > 0:
            percentage_valid = trial.get_percentage_valid(total)
            context['percentage_valid'] = percentage_valid

            solved = trial.get_percentage_solved(total)
            context['percentage_solved'] = solved

            context['percentage_total'] = round((percentage_valid + solved)/2, 2)

        return context


class TrialCreate(SuccessMessageMixin, CreateView):
    model = Trial
    form_class = TrialUploadForm
    template_name_suffix = '_create'
    success_url = reverse_lazy('trials:list')
    success_message = "Trial was created successfully"
    error_message = "Invalid file"

    def form_valid(self, form):
        response = super(SuccessMessageMixin, self).form_valid(form)
        success_message = self.get_success_message(form.cleaned_data)

        if (self.object.id is None):
            messages.error(self.request, self.error_message)
        else:
            messages.success(self.request, success_message)
        return response


class TrialDetail(DetailView):
    model = Trial

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TrialDetail, self).get_context_data(**kwargs)

        # Add in a QuerySet duration
        context['duration'] = context['object'].end_date - context['object'].start_date
        return context


class TrialUpdate(SuccessMessageMixin, UpdateView):
    model = Trial
    form_class = TrialUpdateForm
    template_name_suffix = '_update'
    success_url = reverse_lazy('trials:list')
    success_message = "Trial was updated successfully"


class TrialDelete(RedirectView):
    model = Trial

    def get_redirect_url(self, *args, **kwargs):
        self.url = reverse_lazy('trials:list')
        model = get_object_or_404(Trial, pk=kwargs['pk'])
        try:
            with transaction.atomic():
                # Delete eye data
                TrialData.objects.filter(trial=model.pk).delete()

                # Delete trial
                model.delete()

                # Delete file
                os.unlink(model.file.path)

                messages.success(self.request, 'Trial was deleted successfully')
        except IntegrityError:
            messages.error(self.request, 'The request was unsuccessful')

        return super(TrialDelete, self).get_redirect_url(*args, **kwargs)

eyetracking/apps/trials/templates/trials/trial_actions.html
<a class="btn btn-primary btn-sm tooltip-btn" data-toggle="tooltip" data-placement="top" data-original-title="Update" href="{% url 'trials:update' record.pk %}"><i class="glyphicon glyphicon-edit"></i></a>

<form class="form-inline" method="POST" action="{% url 'trials:delete' record.pk %}">
    {% csrf_token %}
    <button onclick="return confirm('Are you sure you want to delete \'{{ record.name }}\'?')" type="submit" class="btn btn-sm btn-danger tooltip-btn" data-toggle="tooltip" data-placement="top" data-original-title="Delete">
        <i class="glyphicon glyphicon-trash"></i>
    </button>
</form>

eyetracking/apps/trials/templates/trials/trial_create.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %} Upload Trial {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='trials' %}
{% endblock %}

{% block page_title %} Upload Trial {% endblock %}

{% block content %}
	{% include 'trials/trial_form.html' %}
{% endblock %}

eyetracking/apps/trials/templates/trials/trial_detail.html
{% extends "base.html" %}

{% block title %} View Trial {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='trials' %}
{% endblock %}

{% block page_title %} View Trial {% endblock %}

{% block actions %}
    <a class="btn btn-primary" href="{% url 'trials:update' object.pk %}" role="button"><i class="glyphicon glyphicon-edit"></i> Update</a>

    <form class="form-inline" method="POST" action="{% url 'trials:delete' object.pk %}">
        {% csrf_token %}
        <button onclick="return confirm('Are you sure you want to delete?')" type="submit" class="btn btn-danger tooltip-btn" data-toggle="tooltip" data-placement="top" data-original-title="Delete">
            <i class="glyphicon glyphicon-trash"></i> Delete
        </button>
    </form>
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <tr>
            <td><strong>Image</strong></td>
            <td><img class="img-responsive" alt="{{ object.image.original_name }}" src="{{ MEDIA_URL }}{{ object.image.image }}"></td>
        </tr>
        <tr>
            <td><strong>Trial Name</strong></td>
            <td>{{ object.image.original_name }}</td>
        </tr>
        <tr>
            <td><strong>Level</strong></td>
            <td>{{ object.level }}</td>
        </tr>
        <tr>
            <td><strong>Participant</strong></td>
            <td>{{ object.participant.first_name }} {{ object.participant.last_name }}</td>
        </tr>
        <tr>
            <td><strong>Start Date</strong></td>
            <td>{{ object.start_date }}</td>
        </tr>
        <tr>
            <td><strong>End Date</strong></td>
            <td>{{ object.end_date }}</td>
        </tr>
        <tr>
            <td><strong>Duration</strong></td>
            <td>{{ duration }}</td>
        </tr>
        <tr>
            <td><strong>Samples</strong></td>
            <td>{{ object.percentage_samples }} %</td>
        </tr>
        <tr>
            <td><strong>Solved</strong></td>
            <td>
                {% if object.resolved %}
                    <span class="label label-success">Yes</span>
                {% else %}
                    <span class="label label-danger">No</span>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td><strong>Errors</strong></td>
            <td>{{ object.errors }}</td>
        </tr>
        <tr>
            <td><strong>Comments</strong></td>
            <td>{{ object.comments }}</td>
        </tr>
    </table>
{% endblock %}

eyetracking/apps/trials/templates/trials/trial_form.html
{% load bootstrap3 %}

<form method="post" class="form-horizontal" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
      <button type="submit" class="btn btn-primary">Save</button>
  {% endbuttons %}
</form>

eyetracking/apps/trials/templates/trials/trial_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title %} Manage Trials {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='trials' %}
{% endblock %}

{% block page_title %} Manage Trials {% endblock %}

{% block actions %}
    <a class="btn btn-success" href="{% url 'trials:upload' %}" role="button"><i class="fa fa-upload"></i> Upload</a>
{% endblock %}

{% block content %}
    {% include 'trials/trial_search.html' %}

    <div class="container-fluid">
        <div class="col-lg-10">
            {% render_table table "trials/trial_table.html" %}
        </div>
        <div class="col-lg-2 well" style="margin-top: 20px;">
             <div class="col-lg-12" >
                <p>> 80% = {% if percentage_valid %}{{ percentage_valid }}%{% endif %}</p>
                <p>Solved = {{ percentage_solved }} %</p>
                <p>-------------------</p>
                <p>Total = {{ percentage_total }} %</p>
            </div>
        </div>
    </div>
{% endblock %}

eyetracking/apps/trials/templates/trials/trial_search.html
<hr>
<div class="row">
    <div class="col-lg-10">
        <div class="col-lg-6">
        </div>
        <div class="col-lg-6">
            <form role="search">
                <div class="input-group">
                    <input name="search" value="{{ search }}" type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i> </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<br>

eyetracking/apps/trials/templates/trials/trial_table.html
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}

{% if table.page %}
    <div class="table-container">
{% endif %}

{% if table.page %}
    {% with table.page.paginator.count as total %}
    {% with table.page.object_list|length as count %}
        <div class="pull-right">
            {% spaceless %}{% block pagination.cardinality %}{% if total != count %}{% blocktrans %}{{ count }} of {{ total }}{% endblocktrans %}{% else %}{{ total }}{% endif %} {% if total == 1 %}{{ table.data.verbose_name }}{% else %}{{ table.data.verbose_name_plural }}{% endif %}{% endblock pagination.cardinality %}{% endspaceless %}
        </div>
    {% endwith %}
    {% endwith %}
{% endif %}

{% block table %}
    <table class="table table-compact table-bordered table-striped"{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
        {% block table.thead %}
            <thead>
            <tr>
                {% for column in table.columns %}
                    {% if column.orderable %}
                        <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a></th>
                    {% else %}
                        <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
                    {% endif %}
                {% endfor %}
            </tr>
            </thead>
        {% endblock table.thead %}
        {% block table.tbody %}
            <tbody>
            {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
                {% block table.tbody.row %}
                    <tr class="{{ row.tr_class }}">
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{{ cell }}</td>
                        {% endfor %}
                    </tr>
                {% endblock table.tbody.row %}
            {% empty %}
                {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                {% endif %}
            {% endfor %}
            </tbody>
        {% endblock table.tbody %}
        {% block table.tfoot %}
            <tfoot></tfoot>
        {% endblock table.tfoot %}
    </table>
{% endblock table %}

{% if table.page %}
    {% block pagination %}
        {% bootstrap_pagination table.page url=request.get_full_path %}
    {% endblock pagination %}
</div>
{% endif %}

eyetracking/apps/trials/templates/trials/trial_update.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %} Update Trial {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='trials' %}
{% endblock %}

{% block page_title %} Update Trial {% endblock %}

{% block content %}
	{% include 'trials/trial_form.html' %}
{% endblock %}

eyetracking/apps/trials/templates/trials/trialdata_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load staticfiles %}

{% block head_files %}
    <link rel="stylesheet" href="{% static 'statistics/css/plugins/c3/c3.min.css' %}"/>
{% endblock %}

{% block title %} View Data of {{ participant_name }} {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='trials' %}
{% endblock %}

{% block page_title %} View Data of {{ participant_name }} {% endblock %}

{% block content %}
    <hr>
    <h4>Trial {{ image_name }} ({{ duration }})</h4>
    <div class="row">
        <div class="col-lg-12">
            <div id="chart"></div>
        </div>
    </div>
    {% include 'trials/trialdata_search.html' %}
    {% render_table table "table.html" %}
{% endblock %}

{% block body_files_min %}
    <script src="{% static 'statistics/js/plugins/d3/d3.min.js' %}"></script>
    <script src="{% static 'statistics/js/plugins/c3/c3.min.js' %}"></script>
{% endblock %}

{% block body_files %}
    <script src="{% static 'trials/js/trials.js' %}"></script>
    <script>
        generateLineChart({{ raw_pupil }}, {{ smooth_pupil }}, {{ fixed_pupil_distance }}, {{ raw_distance }}, {{ smooth_distance }}, {{ first_index_baseline }}, {{ last_index_baseline }});
    </script>
{% endblock %}

eyetracking/apps/trials/templates/trials/trialdata_search.html
<hr>
<div class="row">
    <div class="col-lg-6">
    </div>
    <div class="col-lg-6">
        <form role="search">
            <div class="input-group">
                <input name="search" value="{{ search }}" type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i> </button>
                </span>
            </div>
        </form>
    </div>
</div>
<br>