eyetracking/apps/aoi/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.AOIList.as_view(), name='list'),
    url(r'^new/$', views.AOICreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/update/$', views.AOIUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', views.AOIDelete.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/change_name/$', views.AOIChangeName.as_view(), name='change_name'),
    url(r'^image/$', views.AOIGetInfoImage.as_view(), name='image'),
    url(r'^shapes/$', views.AOIGetShapes.as_view(), name='shapes'),
]

eyetracking/apps/images/urls.py
from django.conf.urls import url
from django.views.generic import DetailView
from . import views
from .models import Image


urlpatterns = [
    url(r'^$', views.index, name='index_images'),
    url(r'^add$', views.add, name='add_images'),
    url(r'^(?P<pk>\d+)/update$', views.update, name='update_image'),
    url(r'^(?P<pk>\d+)/detail$', DetailView.as_view(model=Image, template_name="images/detail.html"), name="detail_image"),
    url(r'^(?P<pk>\d+)/delete$', views.delete, name='delete_image'),
    url(r'^upload$', views.upload, name='upload_image'),
    url(r'^(?P<pk>\d+)/upload_delete$', views.upload_delete, name='upload_delete'),
]

eyetracking/apps/tracker/urls.py
from django.conf.urls import url
from apps.tracker import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^create$', views.create, name='create_tracker'),
    url(r'^update$', views.update, name='update_tracker'),
    url(r'^detail$', views.detail, name='detail_tracker'),
    url(r'^record$', views.record, name='record_tracker'),
]

eyetracking/eyetracking/urls.py
from django.conf.urls import include, url
from apps.tracker import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^tracker/', include('apps.tracker.urls', namespace='tracker')),
    url(r'^images/', include('apps.images.urls', namespace='images')),
    url(r'^participants/', include('apps.participants.urls', namespace='participants')),
    url(r'^aoi/', include('apps.aoi.urls', namespace='aoi')),
    url(r'^statistics/', include('apps.statistics.urls', namespace='statistics')),
    url(r'^trials/', include('apps.trials.urls', namespace='trials'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eyetracking/templates/base.html
{% load bootstrap3 %}
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
      <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">

            <title>{% block title %} Home {% endblock %} - Pupil Analysis Software</title>

            {% bootstrap_css %}
            <link href="{% static 'css/font_awesome/font-awesome.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/theme/eye_tracking.css' %}" rel="stylesheet">

            <script src="{% static 'js/theme/jquery.min.js' %}"></script>
            {% block head_files_min %}{% endblock %}

            {% compress css %}
                {% block head_files %}{% endblock %}
            {% endcompress %}
      </head>
      <body>
            <nav class="navbar navbar-default navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'tracker:home' %}">Pupil Analysis Software</a>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            {% block menu %} {% endblock %}
                        </ul>
                    </div>
                </div>
            </nav>

            <div class="container">
                <div class="col-lg-12">
                    <div class="col-lg-8">
                        <h1>{% block page_title %} {% endblock %}</h1>
                    </div>
                    <div class="col-lg-4">
                        {% block actions %} {% endblock %}
                    </div>
                </div>
                <div class="col-lg-12">
                    {% block content %}{% endblock %}
                </div>
            </div>

            {% bootstrap_javascript %}
            <script src="{% static 'js/plugins/toastr/toastr.min.js' %}"></script>
            {% block body_files_min %}{% endblock %}

            {% compress js %}
                {% bootstrap_messages %}
                <script>$('.tooltip-btn').tooltip();</script>
                <script src="{% static 'js/theme/eye_tracking.js' %}"></script>
                {% block body_files %}{% endblock %}
            {% endcompress %}
      </body>
</html>

eyetracking/templates/menu.html
<li class="{% if active_menu == 'images' %}active{% endif %}"><a href="{% url 'images:index_images' %}">Images</a></li>
<li class="{% if active_menu == 'aoi' %}active{% endif %}"><a href="{% url 'aoi:list' %}">AOI</a></li>
<li class="{% if active_menu == 'participants' %}active{% endif %}"><a href="{% url 'participants:list' %}">Participants</a></li>
<li class="{% if active_menu == 'trials' %}active{% endif %}"><a href="{% url 'trials:list' %}">Trials</a></li>
<!--<li class="{% if active_menu == 'tracker' %}active{% endif %}"><a href="{% url 'tracker:detail_tracker' %}">Eye Tracker</a></li>-->
<li class="{% if active_menu == 'statistics' %}active{% endif %}"><a href="{% url 'statistics:list' %}">Statistics</a></li>

eyetracking/templates/table.html
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
 
{% if table.page %}
    <div class="table-container">
{% endif %}

{% if table.page %}
    {% with table.page.paginator.count as total %}
    {% with table.page.object_list|length as count %}
        <div class="pull-right">
            {% spaceless %}{% block pagination.cardinality %}{% if total != count %}{% blocktrans %}{{ count }} of {{ total }}{% endblocktrans %}{% else %}{{ total }}{% endif %} {% if total == 1 %}{{ table.data.verbose_name }}{% else %}{{ table.data.verbose_name_plural }}{% endif %}{% endblock pagination.cardinality %}{% endspaceless %}
        </div>
    {% endwith %}
    {% endwith %}
{% endif %}
 
{% block table %}
    <table class="table table-compact table-bordered table-striped"{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
        {% block table.thead %}
            <thead>
            <tr>
                {% for column in table.columns %}
                    {% if column.orderable %}
                        <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a></th>
                    {% else %}
                        <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
                    {% endif %}
                {% endfor %}
            </tr>
            </thead>
        {% endblock table.thead %}
        {% block table.tbody %}
            <tbody>
            {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
                {% block table.tbody.row %}
                    <tr class="{% cycle "odd" "even" %}">
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{{ cell }}</td>
                        {% endfor %}
                    </tr>
                {% endblock table.tbody.row %}
            {% empty %}
                {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                {% endif %}
            {% endfor %}
            </tbody>
        {% endblock table.tbody %}
        {% block table.tfoot %}
            <tfoot></tfoot>
        {% endblock table.tfoot %}
    </table>
{% endblock table %}

{% if table.page %}
    {% block pagination %}
        {% bootstrap_pagination table.page url=request.get_full_path %}
    {% endblock pagination %}
</div>
{% endif %}